from .data import SITE_TYPES, COLOR_SCHEMES


def build_html(site_type_key, form_data, color_scheme_key):
    site_type = SITE_TYPES[site_type_key]
    sections = site_type["sections"]

    section_builders = {
        "hero": _hero_section,
        "about": _about_section,
        "service_times": _service_times_section,
        "contact": _contact_section,
        "mission": _mission_section,
        "cta": _cta_section,
        "footer": _footer_section,
    }

    body_sections = "\n".join(
        section_builders[section](form_data)
        for section in sections
        if section in section_builders
    )

    title = form_data.get("church_name") or form_data.get("ministry_name") or "My Website"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
{body_sections}
    <script src="script.js"></script>
</body>
</html>
"""


def _hero_section(data):
    name = data.get("church_name") or data.get("ministry_name", "")
    tagline = data.get("tagline", "")
    return f"""    <section class="hero">
        <h1>{name}</h1>
        <p class="tagline">{tagline}</p>
    </section>
"""


def _about_section(data):
    about_text = data.get("about_text", "")
    pastor_name = data.get("pastor_name", "")
    return f"""    <section class="about">
        <h2>About Us</h2>
        <p>{about_text}</p>
        {f'<p class="pastor-name">— {pastor_name}, Senior Pastor</p>' if pastor_name else ''}
    </section>
"""


def _service_times_section(data):
    service_times = data.get("service_times", "")
    address = data.get("address", "")
    return f"""    <section class="service-times">
        <h2>Service Times</h2>
        <p>{service_times}</p>
        <p class="address">{address}</p>
    </section>
"""


def _contact_section(data):
    phone = data.get("phone", "")
    email = data.get("email", "") or data.get("contact_email", "")
    return f"""    <section class="contact">
        <h2>Contact Us</h2>
        <p>Phone: {phone}</p>
        <p>Email: {email}</p>
    </section>
"""


def _mission_section(data):
    mission = data.get("mission_statement", "")
    return f"""    <section class="mission">
        <h2>Our Mission</h2>
        <p>{mission}</p>
    </section>
"""


def _cta_section(data):
    cta_text = data.get("cta_text", "Learn More")
    cta_link = data.get("cta_link", "#")
    return f"""    <section class="cta">
        <a href="{cta_link}" class="btn-cta">{cta_text}</a>
    </section>
"""


def _footer_section(data):
    name = data.get("church_name") or data.get("ministry_name", "")
    return f"""    <footer>
        <p>&copy; 2026 {name}. All rights reserved.</p>
    </footer>
"""


def build_css(color_scheme_key):
    scheme = COLOR_SCHEMES[color_scheme_key]
    return f"""* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: Georgia, serif;
    background: {scheme['background']};
    color: {scheme['text']};
    line-height: 1.6;
}}

section {{
    padding: 3rem 1.5rem;
    max-width: 900px;
    margin: 0 auto;
}}

.hero {{
    background: {scheme['primary']};
    color: #ffffff;
    text-align: center;
    padding: 4rem 1.5rem;
}}

.hero h1 {{
    font-size: 2.4rem;
    margin-bottom: 0.5rem;
}}

.hero .tagline {{
    color: {scheme['accent']};
    font-size: 1.2rem;
}}

h2 {{
    color: {scheme['primary']};
    margin-bottom: 1rem;
}}

.btn-cta {{
    display: inline-block;
    background: {scheme['accent']};
    color: {scheme['primary_dark']};
    padding: 0.8rem 2rem;
    border-radius: 4px;
    text-decoration: none;
    font-weight: bold;
}}

.cta {{
    text-align: center;
}}

footer {{
    background: {scheme['primary_dark']};
    color: #ffffff;
    text-align: center;
    padding: 1.5rem;
}}
"""


def build_js():
    return """// Placeholder for future interactivity
console.log("Website generated by InChristAlone AI Studio");
"""

def build_combined_html(html_content, css_content, js_content):
    combined = html_content.replace(
        '<link rel="stylesheet" href="style.css">',
        f'<style>\n{css_content}\n</style>'
    )
    combined = combined.replace(
        '<script src="script.js"></script>',
        f'<script>\n{js_content}\n</script>'
    )
    return combined
